package:
  name: cutadapt
  version: "1.2.1"

source:
  fn: cutadapt-1.2.1.tar.gz
  url: https://pypi.python.org/packages/source/c/cutadapt/cutadapt-1.2.1.tar.gz
  md5: 34dcdf7130d9706f1d7c93c34a26c99b
#  patches:
   # List any patch files here
   # - fix.patch


build:

  detect_binary_files_with_prefix: true 

requirements:
  build:
    - python 2.7*

  run:
    - python 2.7*

#test:
   # Python imports
#   imports:
#     - cutadapt
#     - cutadapt.scripts

about:
  home: http://code.google.com/p/cutadapt/
  license: MIT License
  summary: 'trim adapters from high-throughput sequencing reads'

