package:
  name: cutadapt
  version: "1.8.1"

source:
  fn: cutadapt-1.8.1.tar.gz
  url: https://pypi.python.org/packages/source/c/cutadapt/cutadapt-1.8.1.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch


build:
  number: 0       # (defaults to 0)
  string: monti_0  
  detect_binary_files_with_prefix: true 

requirements:
  build:
    - python 2.7.9

  run:
    - python 2.7.9

#test:
   # Python imports
#   imports:
#     - cutadapt
#     - cutadapt.scripts

about:
  home: http://code.google.com/p/cutadapt/
  license: MIT License
  summary: 'trim adapters from high-throughput sequencing reads'

